'use client';

import Link from 'next/link';
import BackLink from '../components/BackLink';
import SpotlightField from '../components/SpotlightField';

const Arrow = () => <span aria-hidden="true">↗</span>;
const pillars = [
  { href: '/blog/', code: '01', label: 'Blog', title: 'Ideas with a point of view', text: 'Essays, field notes and analysis from the edge of sovereign AI, Web3 and operational security.', accent: 'var(--accent-purple)' },
  { href: '/tutorials/', code: '02', label: 'Tutorials', title: 'Build it locally', text: 'Technical walkthroughs that move from architecture to a working, hardened system.', accent: 'var(--accent-cyan)' },
  { href: '/forge/course/', code: '03', label: 'AI Course', title: 'AI Mastery', text: 'A practical curriculum for building and running personal AI systems with long-term autonomy.', accent: 'var(--accent-orange)' },
];

export default function ForgePage() {
  return <>
    <div className="relative z-10">
      <section className="relative overflow-hidden"><div className="ambient-glow ambient-glow-purple -top-24 left-0 w-[420px] h-[420px] opacity-[0.06]" /><div className="page-container pt-12 md:pt-16 pb-10 md:pb-12 relative"><div className="mb-8"><BackLink fallback="/" label="Home" /></div><div className="grid lg:grid-cols-[1fr_18rem] gap-10 items-end"><div><div className="eyebrow">Forge / transmission</div><h1 className="section-title mt-3 max-w-3xl">Learn the system.<br /><span className="text-[var(--text-secondary)]">Then make it yours.</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-[var(--text-secondary)]">Three ways into the Delta V operating model: ideas to orient you, tutorials to make it real, and courses to build your own foundation.</p></div><SpotlightField kind="forge" /></div></div></section>
      <section className="page-container pb-24" aria-labelledby="forge-pillars"><div className="eyebrow mb-4">The transmission stack</div><h2 id="forge-pillars" className="text-2xl md:text-3xl font-semibold tracking-tight mb-8">Choose your entry point.</h2><div className="grid lg:grid-cols-3 gap-px bg-[var(--border-default)] border border-[var(--border-default)]">{pillars.map((pillar) => <Link key={pillar.href} href={pillar.href} className="capability-card group p-7 md:p-9 min-h-[300px]" style={{ '--pillar-accent': pillar.accent, '--card-accent': pillar.accent } as React.CSSProperties}><div className="flex justify-between font-mono text-xs" style={{ color: pillar.accent }}><span>{pillar.code}</span><Arrow /></div><div className="mt-16"><div className="text-xs uppercase tracking-[.16em]" style={{ color: pillar.accent }}>{pillar.label}</div><h3 className="mt-3 text-2xl font-semibold tracking-tight group-hover:text-[var(--pillar-accent)]">{pillar.title}</h3><p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">{pillar.text}</p></div></Link>)}</div></section>
      <section id="field-labs" className="border-y border-[var(--border-default)] bg-[var(--bg-surface)]"><div className="page-container py-20"><div className="eyebrow text-[var(--accent-orange)]">AI Mastery / future courses</div><h2 className="section-title mt-3 max-w-2xl">Courses that become live systems.</h2><div className="mt-10 divide-y divide-[var(--border-default)] border-y border-[var(--border-default)]"><Link href="/tutorials/hermes-qwen-dgx-spark/" className="forge-course-link group grid md:grid-cols-[7rem_minmax(0,1fr)_9rem] gap-5 py-7"><span className="font-mono text-xs text-[var(--accent-orange)]">COURSE 01</span><span><h3 className="text-xl font-semibold group-hover:text-[var(--accent-orange)]">Open Harness</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">Build an open local AI harness with Hermes today, then extend the pattern to Pi.</p></span><span className="text-sm text-[var(--accent-orange)] justify-self-start">Start here <Arrow /></span></Link><Link href="/forge/course/" className="forge-course-link group grid md:grid-cols-[7rem_minmax(0,1fr)_9rem] gap-5 py-7"><span className="font-mono text-xs text-[var(--accent-cyan)]">COURSE 02</span><span><h3 className="text-xl font-semibold group-hover:text-[var(--accent-cyan)]">Open Design &amp; Workflow Systems</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">A focused path for presentation, video, and specific workflows built around your own operating context.</p></span><span className="text-sm text-[var(--accent-cyan)] justify-self-start">See the path <Arrow /></span></Link><Link href="/forge/x402-workshop/" className="forge-course-link group grid md:grid-cols-[7rem_minmax(0,1fr)_9rem] gap-5 py-7"><span className="font-mono text-xs text-[var(--accent-purple)]">TEASER</span><span><h3 className="text-xl font-semibold group-hover:text-[var(--accent-purple)]">x402 &amp; Agent Payments</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">A future lab for machine-payable services, spend caps, and agent payment flows. More soon.</p></span><span className="text-sm text-[var(--accent-purple)] justify-self-start">Coming soon <Arrow /></span></Link></div></div></section>
    </div>
  </>;
}
